apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  AUTH: "mongodb+srv://admin:bhaNu1136@cluster0.nbzwg6h.mongodb.net/auth"
---
apiVersion: v1
kind: Secret
metadata:
  name: google
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
stringData:
  JWT_SECRET: ""


